### ISSUE TITLE
error for run

### ISSUE THREAD

**Issue by bobwatcherx** [RealBey/ThisIsNotRat#2]
i install add depedecies in requirements.txt and run tinar.py but error

i get error 
```
root@ubun-HP-Convertible-x360-11-ab1XX:/home/ubun/pentester/ThisIsNotRat# python3 tinar.py 
Traceback (most recent call last):
  File "/home/ubun/pentester/ThisIsNotRat/tinar.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

**Comment by ajtazer** [comment]
> i get error

It seems like your existing installations of OpenCV and NumPy are causing conflicts. To resolve this, try completely uninstalling and reinstalling both OpenCV and NumPy before proceeding with the installation of the packages mentioned in the requirements file.
